[package]
name = "altwebgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
axum = "0.7.4"
handlebars = "5.1.0"
http-body-util = "0.1.0"
new_mime_guess = "4.0.1"
tokio = {version="1.36", features = ["macros", "rt-multi-thread"]}
tokio-util = "0.7.10"
tower-http = {version="0.5.2", features = ["fs"]}
tracing = "0.1"
tracing-subscriber = "0.3"
use = "0.0.1-pre.0"
walkdir = "2.5.0"
